### ISSUE TITLE
snapper cannot to be built with btrfs-progs v5.18

### ISSUE THREAD

**Issue by henrich** [openSUSE/snapper#725] opened 2022-05-29 09:16 UTC
Hi,

Recently I've tried to build snapper 0.10.2 on Debian unstable, and it got build failure
since libbtrfs-dev package was updated to 5.18.

```make
/usr/include/btrfs/list.h:78:9: error: expected primary-expression before 'volatile'
   78 |         WRITE_ONCE(list->next, list);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:78:9: error: expected ')' before 'volatile'
   78 |         WRITE_ONCE(list->next, list);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void __list_add(list_head*, list_head*, list_head*)':
/usr/include/btrfs/list.h:116:9: error: expected primary-expression before 'volatile'
  116 |         WRITE_ONCE(prev->next, xnew);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:116:9: error: expected ')' before 'volatile'
  116 |         WRITE_ONCE(prev->next, xnew);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void __list_del(list_head*, list_head*)':
/usr/include/btrfs/list.h:156:9: error: expected primary-expression before 'volatile'
  156 |         WRITE_ONCE(prev->next, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:156:9: error: expected ')' before 'volatile'
  156 |         WRITE_ONCE(prev->next, next);
      |         ^~~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send-utils.h:28,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/list.h: In function 'void list_del(list_head*)':
/usr/include/btrfs/list.h:190:23: error: invalid conversion from 'void*' to 'list_head*' [-fpermissive]
  190 |         entry->next = LIST_POISON1;
      |                       ^~~~~~~~~~~~
      |                       |
      |                       void*
/usr/include/btrfs/list.h:191:23: error: invalid conversion from 'void*' to 'list_head*' [-fpermissive]
  191 |         entry->prev = LIST_POISON2;
      |                       ^~~~~~~~~~~~
      |                       |
      |                       void*
In file included from /usr/include/btrfs/send-utils.h:27,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/list.h: In function 'int list_empty(const list_head*)':
/usr/include/btrfs/list.h:333:16: error: expected primary-expression before 'const'
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
/usr/include/btrfs/list.h:333:16: error: expected ')' before 'const'
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
/usr/include/btrfs/list.h:333:16: error: expected ')' before ';' token
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
/usr/include/btrfs/list.h:333:16: note: to match this '('
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send-utils.h:28,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/list.h:333:38: error: invalid operands of types 'void' and 'const list_head*' to binary 'operator=='
  333 |         return READ_ONCE(head->next) == head;
      |                                      ^~ ~~~~
      |                                         |
      |                                         const list_head*
In file included from /usr/include/btrfs/send-utils.h:27,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/list.h: In function 'void list_del_init_careful(list_head*)':
/usr/include/btrfs/list.h:351:9: error: expected primary-expression before 'volatile'
  351 |         smp_store_release(&entry->next, entry);
      |         ^~~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:351:9: error: expected ')' before 'volatile'
  351 |         smp_store_release(&entry->next, entry);
      |         ^~~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h: In function 'int list_empty_careful(const list_head*)':
/usr/include/btrfs/list.h:369:34: error: expected primary-expression before 'const'
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: error: expected ')' before 'const'
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: error: expected ')' before ';' token
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: note: to match this '('
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: error: void value not ignored as it ought to be
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h: In function 'int hlist_unhashed_lockless(const hlist_node*)':
/usr/include/btrfs/list.h:872:17: error: expected primary-expression before 'const'
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: error: expected ')' before 'const'
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: error: expected ')' before ';' token
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: note: to match this '('
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: error: could not convert '<statement>' from 'void' to 'bool'
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
      |                 |
      |                 void
/usr/include/btrfs/list.h:872:17: error: in argument to unary !
/usr/include/btrfs/list.h: In function 'int hlist_empty(const hlist_head*)':
/usr/include/btrfs/list.h:881:17: error: expected primary-expression before 'const'
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: error: expected ')' before 'const'
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: error: expected ')' before ';' token
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: note: to match this '('
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: error: could not convert '<statement>' from 'void' to 'bool'
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
      |                 |
      |                 void
/usr/include/btrfs/list.h:881:17: error: in argument to unary !
/usr/include/btrfs/list.h: In function 'void __hlist_del(hlist_node*)':
/usr/include/btrfs/list.h:889:9: error: expected primary-expression before 'volatile'
  889 |         WRITE_ONCE(*pprev, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:889:9: error: expected ')' before 'volatile'
  889 |         WRITE_ONCE(*pprev, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:891:17: error: expected primary-expression before 'volatile'
  891 |                 WRITE_ONCE(next->pprev, pprev);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:891:17: error: expected ')' before 'volatile'
  891 |                 WRITE_ONCE(next->pprev, pprev);
      |                 ^~~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send-utils.h:28,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/list.h: In function 'void hlist_del(hlist_node*)':
/usr/include/btrfs/list.h:904:19: error: invalid conversion from 'void*' to 'hlist_node*' [-fpermissive]
  904 |         n->next = LIST_POISON1;
      |                   ^~~~~~~~~~~~
      |                   |
      |                   void*
/usr/include/btrfs/list.h:905:20: error: invalid conversion from 'void*' to 'hlist_node**' [-fpermissive]
  905 |         n->pprev = LIST_POISON2;
      |                    ^~~~~~~~~~~~
      |                    |
      |                    void*
In file included from /usr/include/btrfs/send-utils.h:27,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/list.h: In function 'void hlist_add_head(hlist_node*, hlist_head*)':
/usr/include/btrfs/list.h:933:9: error: expected primary-expression before 'volatile'
  933 |         WRITE_ONCE(n->next, first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:933:9: error: expected ')' before 'volatile'
  933 |         WRITE_ONCE(n->next, first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:935:17: error: expected primary-expression before 'volatile'
  935 |                 WRITE_ONCE(first->pprev, &n->next);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:935:17: error: expected ')' before 'volatile'
  935 |                 WRITE_ONCE(first->pprev, &n->next);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:936:9: error: expected primary-expression before 'volatile'
  936 |         WRITE_ONCE(h->first, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:936:9: error: expected ')' before 'volatile'
  936 |         WRITE_ONCE(h->first, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:937:9: error: expected primary-expression before 'volatile'
  937 |         WRITE_ONCE(n->pprev, &h->first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:937:9: error: expected ')' before 'volatile'
  937 |         WRITE_ONCE(n->pprev, &h->first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void hlist_add_before(hlist_node*, hlist_node*)':
/usr/include/btrfs/list.h:948:9: error: expected primary-expression before 'volatile'
  948 |         WRITE_ONCE(n->pprev, next->pprev);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:948:9: error: expected ')' before 'volatile'
  948 |         WRITE_ONCE(n->pprev, next->pprev);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:949:9: error: expected primary-expression before 'volatile'
  949 |         WRITE_ONCE(n->next, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:949:9: error: expected ')' before 'volatile'
  949 |         WRITE_ONCE(n->next, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:950:9: error: expected primary-expression before 'volatile'
  950 |         WRITE_ONCE(next->pprev, &n->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:950:9: error: expected ')' before 'volatile'
  950 |         WRITE_ONCE(next->pprev, &n->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:951:9: error: expected primary-expression before 'volatile'
  951 |         WRITE_ONCE(*(n->pprev), n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:951:9: error: expected ')' before 'volatile'
  951 |         WRITE_ONCE(*(n->pprev), n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void hlist_add_behind(hlist_node*, hlist_node*)':
/usr/include/btrfs/list.h:962:9: error: expected primary-expression before 'volatile'
  962 |         WRITE_ONCE(n->next, prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:962:9: error: expected ')' before 'volatile'
  962 |         WRITE_ONCE(n->next, prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:963:9: error: expected primary-expression before 'volatile'
  963 |         WRITE_ONCE(prev->next, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:963:9: error: expected ')' before 'volatile'
  963 |         WRITE_ONCE(prev->next, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:964:9: error: expected primary-expression before 'volatile'
  964 |         WRITE_ONCE(n->pprev, &prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:964:9: error: expected ')' before 'volatile'
  964 |         WRITE_ONCE(n->pprev, &prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:967:17: error: expected primary-expression before 'volatile'
  967 |                 WRITE_ONCE(n->next->pprev, &n->next);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:967:17: error: expected ')' before 'volatile'
  967 |                 WRITE_ONCE(n->next->pprev, &n->next);
      |                 ^~~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send-utils.h:28,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/list.h: At global scope:
/usr/include/btrfs/list.h:1015:55: error: expected ',' or '...' before 'new'
 1015 |                                    struct hlist_head *new)
      |                                                       ^~~
/usr/include/btrfs/list.h: In function 'void hlist_move_list(hlist_head*, hlist_head*)':
/usr/include/btrfs/list.h:1017:12: error: expected type-specifier before '->' token
 1017 |         new->first = old->first;
      |            ^~
/usr/include/btrfs/list.h:1018:16: error: expected type-specifier before '->' token
 1018 |         if (new->first)
      |                ^~
/usr/include/btrfs/list.h:1018:16: error: expected ')' before '->' token
 1018 |         if (new->first)
      |            ~   ^~
      |                )
/usr/include/btrfs/list.h:1019:20: error: expected type-specifier before '->' token
 1019 |                 new->first->pprev = &new->first;
      |                    ^~
In file included from /usr/include/btrfs/send-utils.h:27,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/extent-cache.h: In function 'int cache_tree_empty(cache_tree*)':
/usr/include/btrfs/extent-cache.h:78:16: error: expected primary-expression before 'const'
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
/usr/include/btrfs/extent-cache.h:78:16: error: expected ')' before 'const'
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
/usr/include/btrfs/extent-cache.h:78:16: error: expected ')' before ';' token
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
/usr/include/btrfs/extent-cache.h:78:16: note: to match this '('
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
In file included from /usr/include/btrfs/extent-cache.h:27,
                 from /usr/include/btrfs/ctree.h:33,
                 from /usr/include/btrfs/send-utils.h:28,
                 from BtrfsUtils.cc:36:
/usr/include/btrfs/extent-cache.h:78:16: error: invalid operands of types 'void' and 'long int' to binary 'operator=='
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^
In file included from /usr/include/btrfs/list.h:25,
                 from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h: In function 'void INIT_LIST_HEAD(list_head*)':
/usr/include/btrfs/list.h:78:9: error: expected primary-expression before 'volatile'
   78 |         WRITE_ONCE(list->next, list);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:78:9: error: expected ')' before 'volatile'
   78 |         WRITE_ONCE(list->next, list);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void __list_add(list_head*, list_head*, list_head*)':
/usr/include/btrfs/list.h:116:9: error: expected primary-expression before 'volatile'
  116 |         WRITE_ONCE(prev->next, xnew);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:116:9: error: expected ')' before 'volatile'
  116 |         WRITE_ONCE(prev->next, xnew);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void __list_del(list_head*, list_head*)':
/usr/include/btrfs/list.h:156:9: error: expected primary-expression before 'volatile'
  156 |         WRITE_ONCE(prev->next, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:156:9: error: expected ')' before 'volatile'
  156 |         WRITE_ONCE(prev->next, next);
      |         ^~~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h: In function 'void list_del(list_head*)':
/usr/include/btrfs/list.h:190:23: error: invalid conversion from 'void*' to 'list_head*' [-fpermissive]
  190 |         entry->next = LIST_POISON1;
      |                       ^~~~~~~~~~~~
      |                       |
      |                       void*
/usr/include/btrfs/list.h:191:23: error: invalid conversion from 'void*' to 'list_head*' [-fpermissive]
  191 |         entry->prev = LIST_POISON2;
      |                       ^~~~~~~~~~~~
      |                       |
      |                       void*
In file included from /usr/include/btrfs/list.h:25,
                 from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h: In function 'int list_empty(const list_head*)':
/usr/include/btrfs/list.h:333:16: error: expected primary-expression before 'const'
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
/usr/include/btrfs/list.h:333:16: error: expected ')' before 'const'
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
/usr/include/btrfs/list.h:333:16: error: expected ')' before ';' token
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
/usr/include/btrfs/list.h:333:16: note: to match this '('
  333 |         return READ_ONCE(head->next) == head;
      |                ^~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h:333:38: error: invalid operands of types 'void' and 'const list_head*' to binary 'operator=='
  333 |         return READ_ONCE(head->next) == head;
      |                                      ^~ ~~~~
      |                                         |
      |                                         const list_head*
In file included from /usr/include/btrfs/list.h:25,
                 from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h: In function 'void list_del_init_careful(list_head*)':
/usr/include/btrfs/list.h:351:9: error: expected primary-expression before 'volatile'
  351 |         smp_store_release(&entry->next, entry);
      |         ^~~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:351:9: error: expected ')' before 'volatile'
  351 |         smp_store_release(&entry->next, entry);
      |         ^~~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h: In function 'int list_empty_careful(const list_head*)':
/usr/include/btrfs/list.h:369:34: error: expected primary-expression before 'const'
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: error: expected ')' before 'const'
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: error: expected ')' before ';' token
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: note: to match this '('
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h:369:34: error: void value not ignored as it ought to be
  369 |         struct list_head *next = smp_load_acquire(&head->next);
      |                                  ^~~~~~~~~~~~~~~~
/usr/include/btrfs/list.h: In function 'int hlist_unhashed_lockless(const hlist_node*)':
/usr/include/btrfs/list.h:872:17: error: expected primary-expression before 'const'
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: error: expected ')' before 'const'
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: error: expected ')' before ';' token
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: note: to match this '('
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:872:17: error: could not convert '<statement>' from 'void' to 'bool'
  872 |         return !READ_ONCE(h->pprev);
      |                 ^~~~~~~~~
      |                 |
      |                 void
/usr/include/btrfs/list.h:872:17: error: in argument to unary !
/usr/include/btrfs/list.h: In function 'int hlist_empty(const hlist_head*)':
/usr/include/btrfs/list.h:881:17: error: expected primary-expression before 'const'
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: error: expected ')' before 'const'
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: error: expected ')' before ';' token
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: note: to match this '('
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
/usr/include/btrfs/list.h:881:17: error: could not convert '<statement>' from 'void' to 'bool'
  881 |         return !READ_ONCE(h->first);
      |                 ^~~~~~~~~
      |                 |
      |                 void
/usr/include/btrfs/list.h:881:17: error: in argument to unary !
/usr/include/btrfs/list.h: In function 'void __hlist_del(hlist_node*)':
/usr/include/btrfs/list.h:889:9: error: expected primary-expression before 'volatile'
  889 |         WRITE_ONCE(*pprev, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:889:9: error: expected ')' before 'volatile'
  889 |         WRITE_ONCE(*pprev, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:891:17: error: expected primary-expression before 'volatile'
  891 |                 WRITE_ONCE(next->pprev, pprev);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:891:17: error: expected ')' before 'volatile'
  891 |                 WRITE_ONCE(next->pprev, pprev);
      |                 ^~~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h: In function 'void hlist_del(hlist_node*)':
/usr/include/btrfs/list.h:904:19: error: invalid conversion from 'void*' to 'hlist_node*' [-fpermissive]
  904 |         n->next = LIST_POISON1;
      |                   ^~~~~~~~~~~~
      |                   |
      |                   void*
/usr/include/btrfs/list.h:905:20: error: invalid conversion from 'void*' to 'hlist_node**' [-fpermissive]
  905 |         n->pprev = LIST_POISON2;
      |                    ^~~~~~~~~~~~
      |                    |
      |                    void*
In file included from /usr/include/btrfs/list.h:25,
                 from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h: In function 'void hlist_add_head(hlist_node*, hlist_head*)':
/usr/include/btrfs/list.h:933:9: error: expected primary-expression before 'volatile'
  933 |         WRITE_ONCE(n->next, first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:933:9: error: expected ')' before 'volatile'
  933 |         WRITE_ONCE(n->next, first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:935:17: error: expected primary-expression before 'volatile'
  935 |                 WRITE_ONCE(first->pprev, &n->next);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:935:17: error: expected ')' before 'volatile'
  935 |                 WRITE_ONCE(first->pprev, &n->next);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:936:9: error: expected primary-expression before 'volatile'
  936 |         WRITE_ONCE(h->first, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:936:9: error: expected ')' before 'volatile'
  936 |         WRITE_ONCE(h->first, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:937:9: error: expected primary-expression before 'volatile'
  937 |         WRITE_ONCE(n->pprev, &h->first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:937:9: error: expected ')' before 'volatile'
  937 |         WRITE_ONCE(n->pprev, &h->first);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void hlist_add_before(hlist_node*, hlist_node*)':
/usr/include/btrfs/list.h:948:9: error: expected primary-expression before 'volatile'
  948 |         WRITE_ONCE(n->pprev, next->pprev);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:948:9: error: expected ')' before 'volatile'
  948 |         WRITE_ONCE(n->pprev, next->pprev);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:949:9: error: expected primary-expression before 'volatile'
  949 |         WRITE_ONCE(n->next, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:949:9: error: expected ')' before 'volatile'
  949 |         WRITE_ONCE(n->next, next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:950:9: error: expected primary-expression before 'volatile'
  950 |         WRITE_ONCE(next->pprev, &n->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:950:9: error: expected ')' before 'volatile'
  950 |         WRITE_ONCE(next->pprev, &n->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:951:9: error: expected primary-expression before 'volatile'
  951 |         WRITE_ONCE(*(n->pprev), n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:951:9: error: expected ')' before 'volatile'
  951 |         WRITE_ONCE(*(n->pprev), n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h: In function 'void hlist_add_behind(hlist_node*, hlist_node*)':
/usr/include/btrfs/list.h:962:9: error: expected primary-expression before 'volatile'
  962 |         WRITE_ONCE(n->next, prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:962:9: error: expected ')' before 'volatile'
  962 |         WRITE_ONCE(n->next, prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:963:9: error: expected primary-expression before 'volatile'
  963 |         WRITE_ONCE(prev->next, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:963:9: error: expected ')' before 'volatile'
  963 |         WRITE_ONCE(prev->next, n);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:964:9: error: expected primary-expression before 'volatile'
  964 |         WRITE_ONCE(n->pprev, &prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:964:9: error: expected ')' before 'volatile'
  964 |         WRITE_ONCE(n->pprev, &prev->next);
      |         ^~~~~~~~~~
/usr/include/btrfs/list.h:967:17: error: expected primary-expression before 'volatile'
  967 |                 WRITE_ONCE(n->next->pprev, &n->next);
      |                 ^~~~~~~~~~
/usr/include/btrfs/list.h:967:17: error: expected ')' before 'volatile'
  967 |                 WRITE_ONCE(n->next->pprev, &n->next);
      |                 ^~~~~~~~~~
In file included from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/list.h: At global scope:
/usr/include/btrfs/list.h:1015:55: error: expected ',' or '...' before 'new'
 1015 |                                    struct hlist_head *new)
      |                                                       ^~~
/usr/include/btrfs/list.h: In function 'void hlist_move_list(hlist_head*, hlist_head*)':
/usr/include/btrfs/list.h:1017:12: error: expected type-specifier before '->' token
 1017 |         new->first = old->first;
      |            ^~
/usr/include/btrfs/list.h:1018:16: error: expected type-specifier before '->' token
 1018 |         if (new->first)
      |                ^~
/usr/include/btrfs/list.h:1018:16: error: expected ')' before '->' token
 1018 |         if (new->first)
      |            ~   ^~
      |                )
/usr/include/btrfs/list.h:1019:20: error: expected type-specifier before '->' token
 1019 |                 new->first->pprev = &new->first;
      |                    ^~
In file included from /usr/include/btrfs/list.h:25,
                 from /usr/include/btrfs/ctree.h:31,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/extent-cache.h: In function 'int cache_tree_empty(cache_tree*)':
/usr/include/btrfs/extent-cache.h:78:16: error: expected primary-expression before 'const'
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
/usr/include/btrfs/extent-cache.h:78:16: error: expected ')' before 'const'
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
/usr/include/btrfs/extent-cache.h:78:16: error: expected ')' before ';' token
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
/usr/include/btrfs/extent-cache.h:78:16: note: to match this '('
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^~~~~~~~~~~~~
In file included from /usr/include/btrfs/extent-cache.h:27,
                 from /usr/include/btrfs/ctree.h:33,
                 from /usr/include/btrfs/send.h:26,
                 from Btrfs.cc:41:
/usr/include/btrfs/extent-cache.h:78:16: error: invalid operands of types 'void' and 'long int' to binary 'operator=='
   78 |         return RB_EMPTY_ROOT(&tree->root);
      |                ^
make[3]: *** [Makefile:596: BtrfsUtils.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:596: Btrfs.lo] Error 1
```

**Comment by aschnell** [comment] 2022-05-30 05:23
Looks more like a problem of btrfs. I will ask for experts to have a look.

**Comment by kdave** [comment] 2022-05-30 10:44
Yeah it's caused by a recent update in btrfs-progs, after syncing more of the kernel headers.

**Comment by kdave** [comment] 2022-05-30 10:58
This is a C vs C++ types issue, can be reproduced in btrfs-progs by `make CC=g++` too, but I don't see a quick fix other than reverting the recent changes.

**Comment by kdave** [comment] 2022-05-30 14:00
Fixed in the devel branch, I'll do a release soon as there are some other fixes pending.

**Comment by kdave** [comment] 2022-06-06 20:54
btrfs-progs 5.18.1 released today with the fix.

**Comment by aschnell** [comment] 2022-06-07 06:33
Thanks, closing.

**Closed by aschnell** 2022-06-07 06:33 UTC
Labels: bug
